version: '3'

networks:
    xarxa_gp1f5a1:
        driver: bridge

services:
    a_t:
        image: a_t
        expose:
            - "8000"
        volumes:
            - ./app:/var/www/html
        networks:
            - xarxa_gp1f5a1
    lb:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - a_t
        ports:
            - "8081:8081"
        networks:
            - xarxa_gp1f5a1
